### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Kaapo38** [vince1444/r6-api#1]
Add error handling for when a player is not found so the whole thing won't crash

**Comment by vincecorradetti** [comment]
@Kaapo38 Hi, just wanted to inform you that I don't think I'll have time to work on this in the foreseeable future. I'll try to add some error handling when I get a chance though. ~~You can probably edit the main file and remove the lines where it says `throw new Error(e)` (like in like 60). If you get a chance, let me know and if it works you can make a pull request and I'll test it out & merge. Edit: It actually doesn't seem too hard now that I'm explaining it to you.~~ Edit 2: Might have to refactor a lot of the code. I might have a chance to work on it in the next few weeks but I'm juggling a few different things right now so don't count on it.

**Comment by Kaapo38** [comment]
ok, no worries mate, do your own stuff first that's more important 😉

**Comment by vincecorradetti** [comment]
Fixed in Pull Request #3. Definitely want to add more error handling in the future though.
